service: ruby-europe
image: rubyeurope/rubyeurope.com

servers:
  web:
    hosts:
      - 64.227.117.90
proxy:
  app_port: 3000
  ssl: true
  hosts:
    - rubyeurope.com
    - www.rubyeurope.com
  healthcheck:
    interval: 2

registry:
  server: ghcr.io
  username: KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    WEB_CONCURRENCY: 0
    RAILS_ENV: production
    HOST: rubyeurope.com
  secret:
    - SECRET_KEY_BASE
